### ISSUE TITLE
Media storage into GCS isn't working

### ISSUE THREAD

**Issue by engmsaleh** [presslabs/stack#94]
**What happened**:
I have configured helm chat to use GCS as the place to save media instead of `uploads` folder, but it didn't work and kept using `uploads` folder

**What you expected to happen**:
I have added the config as follows in the `values.yaml`
```
media:
  gcs:
    # google cloud project
    project: <project_name>
    # bucket name
    bucket: <bucket_name>
    # use a prefix inside the bucket to store the media files
    prefix: media/
    # credentials to access Google Cloud Storage
    google_credentials: '<JSON file content>'
```
**How to reproduce it (as minimally and precisely as possible)**:
Try it as advised in docs
